### ISSUE TITLE
Merge with Stardust?

### ISSUE THREAD

**Issue by TimNZ** [hallister/semantic-react#122]
I'm definitely not of the opinion there should only be one version of anything, but in this case does it make sense to merge the expert dev of semantic-react  with Stardust?

https://github.com/TechnologyAdvice/stardust

**Comment by asvetliakov** [comment]
We had some discussion with TA folks some time ago about this, that wouldn't going to be happen. The reason is the different ways to expose API for consumer and produce final html markup. stardust is going this way:
```jsx
<List>
  <ListItem>
   <ListItem.Header>
     <ListItem.Icon/>
   </ListItem.Header>
   <ListItem.Image/>
  </ListItem>
etc...
</List>
```
i.e they're making separate subcomponents for different parent contexts (items,cards,menu,modal,etc..). Although this is semantically correct (because header in list doesn't support all ordinary header properties) and restricts using these elements to produce only correct markup, i don't think that is correct API to consume. 
semantic-react is going by different way: we're only handling using of ```ui``` class in these components and removing it by parent context (using react context types) but reusing same standalone components:
```jsx
<List>
  <ListItem>
     <Header/>
     <Icon/>
     <Image/>
  </ListItem>
</List>
```
Here Header, Icon and Image are same as standalone components. They have same propTypes and you can break layout if you pass some prop that's not suitable for semantic CSS.

**Comment by TimNZ** [comment]
Fair enough, thanks.

**Comment by TimNZ** [comment]
Sorry just saw #62
