### ISSUE TITLE
Comparing with react-semantify

### ISSUE THREAD

**Issue by xmehaut** [hallister/semantic-react#27]
Hello
Thanks for this great work by porting semantic ui on react.
I personnaly use react with typescript, and l.m currently moving from bootstrap to semantic, while still using some compoent from material-ui too.
My question is the following : react-semantify already exists. What are the differences, the advantages and drawbacks to use semantic-react instead? Why not merging the two projects?
Best regards

**Comment by hallister** [comment]
react-semantify is actually just bindings for semantic-ui's existing javascript. So you'll need react-semantify, semantic-ui and jquery installed to use it. That's around 400kb minified in overhead. That doesn't include React itself.

semantic-react (in its current state) is around 178kb, and there are no external dependencies besides React and ReactDOM. However, it isn't complete as of yet. I expect, once complete, the file size to be under 250kb, but it will likely be around 200kb. Additionally, semantic-react uses react for any DOM changes. All animations are style-based, so we don't touch the DOM without React knowing.

All in all, it will depend a bit on your current stack. If you aren't using jquery, you don't mind the components that aren't complete and you are comfortable using semantic-react in its (very) beta state, you can jump in. Otherwise, react-semantify is definitely an option.

**Comment by xmehaut** [comment]
Hi Justin,

thanks for this good explanation (mybe to put in the readme.md on gitub).
It is actually valuable not to be connected to jquery if not necessary, and
to be able to think in term of independant web components we may mix with
other react components even if not related to semantic-ui.
I personnaly use jspm/systemjs for incrementally load components, so the
size is less a concern for me, even if it is important.
What I like in bootstrap an semantic-ui, is the ability to make quick
mockups directly in html without having to create a react test app... Once
my design is stable, then I start to develop in react... This lyfe cycle is
fundamental for me, and it is why it seems to me important to keep css
configuration outside the react components in the way semantic has chosen
through for instance the theme.config file...

best regards

2015-12-15 5:01 GMT+01:00 Justin Hall <notifications@github.com>:
