### ISSUE TITLE
Install and run pbs

### ISSUE THREAD

**Issue by xmehaut** [hallister/semantic-react#28]
Hello
I've just downloaded semantic-react, made the npm install then start, and tried to launch it in the browser without success, in order to see how to use the components (like for instance the modal component - why are there two files modal and modal-body for instance, and how to use them)..
Have you got a working web site where we could browse the doc without having to install it locally?

best regards

**Comment by hallister** [comment]
The documentation is a work-in-progress at this point, so there isn't much to look at. There probably won't be completed docs for some time, as the project is still pretty young. Until then, a lot of the components you'll have to either look at the documentation source, or just look at the source of the component itself to reason about how it works.

The Model component is in two parts for technical reasons, but an end-user should just use a `Model`. The `ModelBody` is created by the `Model` so that clicks outside of the `Model` can be detected (clicking on the backdrop).

Best advice is to look at the component source and the proptypes and compare that against the documentation for Semantic-UI to get an idea of how things work.

**Comment by xmehaut** [comment]
ReHi Justin,

could you give me just a simple example (for instance a Button with
animated props) of a call of a component?
e.g <Button ...
just to see the syntax
best regards
Xavier

2015-12-15 10:30 GMT+01:00 Justin Hall <notifications@github.com>:

**Comment by xmehaut** [comment]
oki, I found , e.g. :

            <Icons size="huge">
                <Icon size="big thin" name="circle"></Icon>
                <Icon name="user"></Icon>
            </Icons>

            <Icons size="huge">
              <Icon size="big" color="red" name="dont"></Icon>
              <Icon color="black" name="user"></Icon>
            </Icons>

            <Icons size="huge">
              <Icon size="big" loading name="sun"></Icon>
              <Icon name="user "></Icon>
            </Icons>

or

            <Icon  disabled color="orange" rotated="counterclockwise"
name="star"> </Icon>
             <Icon  name="spinner" loading ></Icon>
            <Icon  name="circle notched" loading ></Icon>
            <Icon  name="asterisk" loading ></Icon>
            <Icon  fitted name="help" ></Icon>

            <Icon  size="mini" name="home" ></Icon>
            <Icon  size="tiny" name="home" ></Icon>
            <Icon  size="small" name="home" ></Icon>
            <Icon  name="home"></Icon>
            <Icon  size="large" name="home"></Icon>
            <Icon  size="big" name="home"></Icon>
            <Icon  size="huge" name="home"></Icon>
            <Icon  size="massive" name="home"></Icon>
            <Icon  color="red" name="users"></Icon>

2015-12-15 10:30 GMT+01:00 Justin Hall <notifications@github.com>:
