### ISSUE TITLE
[Discussion]: Vision and goals for this project

### ISSUE THREAD

**Issue by justingreenberg** [hallister/semantic-react#5]
Let me begin by saying you have done some awesome work here. I started converting a few semantic components to react a few months ago and and quickly gave up—even though most of the logic is already written (in jquery), porting it to react is easier said than done. I decided to wait for stateless components in 0.14, which I see you are using extensively :+1: 

I would definitely like to get involved in my free time. I have a couple of questions...

1. It looks like you are using an IDE based of the .idea folder, what are you using?

2. Based on the buttondocs.js it looks like you are trying to replicate similar functionality to the Semantic UI docs site. Personally, I found their docs, apis, and terminology to be extremely confusing—I think it's a big reason why it hasn't hit the adoption levels of bootstrap, which is ironic considering they are trying to make things simpler. I would suggest modeling this project documentation after the http://material-ui.com docs, which I find extremely intuitive. 

**also a quick little bug report....** karma throws bc of es6 file extension on `modules/animate/jql.es6`... even though webpack is resolving, regex test isn't returning it to `componentContext` in `src/app.tests`... so just gotta update the regex or change the file extension to jsx

**Comment by hallister** [comment]
> It looks like you are using an IDE based of the .idea folder, what are you using? Looks interesting

I started with WebStorm but moved to atom for this project. A fully-fledged IDE got in my way more than it helped since all of the components are independent, and editor ended up being more than enough.

> Based on the buttondocs.js it looks like you are trying to replicate similar functionality to the Semantic UI docs site. Personally, I found their docs, apis, and terminology to be extremely confusing

I agree. My initial goal was to replicate it, but since I don't even like them I'm thinking a new direction is the best approach. I've gotten pretty close to completion on the core Semantic library, and after that, I'll probably move to MUCH simpler docs.

>  I would suggest modeling this project documentation after the http://material-ui.com docs, which I find extremely intuitive.

That's a very good idea, and the simple interface means implementing it should be pretty easy.

> karma throws bc of es6 file extension on modules/animate/jql.es6

Nice catch! I need to rename the file to rquery anyway, so I'll do that at some point today.

**Comment by justingreenberg** [comment]
Sounds good! I know you're close to the finish line on core. I don't want to get in the way, so whenever you're comfortable that components are relatively stable, I would be happy to help with prototyping and developing the new documentation. Let me know! :)

**Comment by jeffscottward** [comment]
+1. I think this is a great initiative.

Many on my team @ConsenSys are digging react but the reliance on jQuery and the dependency of doing a second update for Semantic components after an update is kind of a non-starter.

I think I may attack forms w/ you as that is the highest priority (for both you and probably us).

**Comment by hallister** [comment]
@justingreenberg I'm pretty close on the core API for the elements, views and collections being complete so prototyping and docs are just around the corner. Thanks for the offer and will let you know as soon as I'm ready!

@jeffscottward Sounds great! My current goal was complete the remainder of the views/collections, including forms, this week or early next week so any assistance will help greatly.

**Comment by hallister** [comment]
@jeffscottward I pushed an update which includes basic forms support. The current checkbox module does not work with it, so I'll need to make modifications to that, but otherwise it appears to be working.

**Comment by justingreenberg** [comment]
@hallister semantic maintains an npm package `semantic-ui-css` which we can add to dependencies and import css directly in corresponding component files using webpack, ie...

add css loader to webpack config:
```javascript
{
  test: /\.css$/,
  loaders: [
    'style-loader',
    'css-loader'
  ]
}
```

import styles for button component (in button.jsx)
```javascript
import 'semantic-ui-css/components/button.css';
```

i have only tested it with a few components but everything seems to be working... what do you think?

we could take it a step further and [use the less distribution](https://github.com/Semantic-Org/Semantic-UI-LESS) which would provide easy access to raw variables for theming

**Comment by hallister** [comment]
@justingreenberg That is definitely an option.

This is actually an area where I'm still struggling what to do. There are a number of caveats for each so it's mostly deciding which are the most tasteful.

1. Leave it as is and allow theming through LESS/SASS variables as Semantic suggests.
2. Import the LESS and allow for props to handle variables.
3. Remove the Semantic dependency all together and use something like [JSXStyle](https://github.com/petehunt/jsxstyle).

The first makes this project entirely reliant using Semantic's build system to support theming, which I don't like. The second means implementing tracking theming internally to the project, but having to support Semantic's LESS API in order to do it. The third makes maintenance much more difficult and the scope of the project much larger.

The biggest reason I'm leaning towards 3 is because Semantic is broken in several cases when used with React. This is due to their over-reliance on pseudo-classes like `:first-child`, `:last-child`, `:not:`, etc. Its what is forcing us to use contexts in really awkward ways due to how they use the `ui` class. It's causing bugs with some components, particularly anything with free-floating text, since React has to add spans. And in the case of `Statistic` the text version of it can't be done because of Semantic's `:first-child` and `:last-child` usage.

I'm still not sure which direction is the right one. At this point I would like to complete all of the components and have a usable UI and once that's complete take a closer look at the options.

**Comment by justingreenberg** [comment]
@hallister i completely agree finishing components is first priority! a couple of thoughts....

i would be hesitant to remove the semantic dependency altogether—i just feel like manually monitoring and porting bug fixes and other updates from the (huge) source repo would ultimately become unmaintainable. it would also generally eschew the community benefits of a project with 20k+ stargazers. 

so, maybe leverage one of the npm distributions (either css or less) with webpack to bundle component modules with their styles (ie just `import {Button} from 'semantic-react/components/elements'`)...

- **css-loader** (as described above):  would improve modularity, very easy to implement, low hanging fruit... but wouldn't address react issues related to pseudo-classes. 

- **less-loader**: using webpack loader instead of semantic's (absolutely awful) build system, we could place variables.less and overrides.less files in app styles directory that could be manually customized, or theme styles could be pasted in from a `semantic-ui/src/themes` folder. this would provide much more flexible theming, but also wouldn't address react issues related to pseudo-classes. 

just some thoughts, let me know what you think. if you want me to put together a PR for either solution above i'd be happy to. along those lines, i had a quick question... how are you viewing rendered components and confirming functionality as you develop them? are you kinda just rendering them one at a time in app.jsx as you build them, then moving jsx to doc files? i know some of the docs include a bunch of component variations. since you indicated you were interested in going another direction with the docs, i assume you are not still building them? just trying to see where you're at and what your workflow looks like. looking forward to jumping in.

**Comment by hallister** [comment]
@justingreenberg I agree with your first point. My plan for the time being was to finish everything and get various browser tests done and then see if I can build a diffing tool to automate the process to some degree. That said, that's probably step 283 and I'm still working on step 1, so there are no plans to do that in the immediate future.

I'm definitely not opposed to the less-loader. I hate Semantic's build system with a passion. Honestly the pseudo-class problems aren't going to get solved today, so I'm okay with just pretending Statistic  doesn't exist to make the remainder of the library functional.

>  are you kinda just rendering them one at a time in app.jsx as you build them, then moving jsx to doc files

I'm not even doing that at this point. Now I'm testing them in app.jsx and once I have tested every option I just move on. I really liked the React Material docs you linked to, so if we can borrow that design (but allow for multiple component options to render without it being cluttered) that's probably a good direction. The only reason the existing docs are still there is because it saves me from typing the various variations that I've already done. 

If you are interested in the docs (in addition to your less-loader idea) feel free to create a new docs directory at the root of the project (where it should be lol) and have at it!

**Comment by hallister** [comment]
Going to close this in favor of #62 since this is pretty dated at this point.
