### ISSUE TITLE
How to make this work (eager beta tester)

### ISSUE THREAD

**Issue by tomitrescak** [hallister/semantic-react#59]
Hi, I would love to give your project a go in Meteor as it looks awesome.
I tried downloading the source and linking it to one of my projects, but the moment I reference an element, e.g. Form I receive a following error in the console:

```
W20160322-19:09:40.227(11)? (STDERR) TypeError: Cannot read property 'TransitionGroup' of undefined
W20160322-19:09:40.227(11)? (STDERR)     at Object.module.exports (server.js:1101:1)
W20160322-19:09:40.227(11)? (STDERR)     at __webpack_require__ (server.js:24:1)
W20160322-19:09:40.227(11)? (STDERR)     at Object.eval (eval at <anonymous> (server.js:1095:1), <anonymous>:26:35)
W20160322-19:09:40.227(11)? (STDERR)     at Object.module.exports (server.js:1095:1)
W20160322-19:09:40.227(11)? (STDERR)     at __webpack_require__ (server.js:24:1)
W20160322-19:09:40.227(11)? (STDERR)     at Object.eval (eval at <anonymous> (server.js:1041:1), <anonymous>:52:19)
W20160322-19:09:40.228(11)? (STDERR)     at Object.module.exports (server.js:1041:1)
W20160322-19:09:40.228(11)? (STDERR)     at __webpack_require__ (server.js:24:1)
W20160322-19:09:40.228(11)? (STDERR)     at Object.eval (eval at <anonymous> (server.js:801:1), <anonymous>:26:16)
W20160322-19:09:40.228(11)? (STDERR)     at Object.module.exports (server.js:801:1)
```

**Comment by tomitrescak** [comment]
When I commented out animations.js all worked ok. There seems to be issue with react animations components.

**Comment by asvetliakov** [comment]
You need to install react-addons-transition-group for now. It's obsoleted (since we're moving to react-motion and react-motion-ui-pack) , but few components are still using it

**Comment by tomitrescak** [comment]
Also, I had to import the whole "semantic-ui-css" to make it work. Would you consider to push maybe another pre-release to npmjs so that we can test it out? I am already using it in one of my projects and it massively simplifies testing using Enzyme.

**Comment by asvetliakov** [comment]
@tomitrescak You need semantic css yes, since this lib doesn't include any semantic css classes or styles (i think it's out of scope of current project).
regarding pre-release, it's a good idea, but need to finish few things for now:
1) Rework modal & Checkbox
2) Delete old animation stuff
3) Provide documentation for most components
I think these things will be done in next 1 or 1.5 months

You can use github version in your project, just include:
```
"semantic-react": "hallister/semantic-react"
```
but API is subject to change without any notice, so i'd recommend to add hash tag to prevent this.

**Comment by tomitrescak** [comment]
Thanks @asvetliakov I'll try to pitch in with some PRs as well.

**Comment by tomitrescak** [comment]
Just an idea, you should maybe import the semantic-ui CSS components in each of the React components so that the CSS will get imported only when it's really needed.

Example in React button:

```
import 'semantic-ui-css/components/button.css'
...
// button code
```

One problem here is that if people decide to use the LESS version you are forcing them to include CSS as well.

**Comment by asvetliakov** [comment]
Yes, the problem that it's forcing to use css version with default variables/theme. For example we're using few different themes rather than default for components. Thus this will need a way to provide theming for components as well as a way for defining custom variables (for theme level and for signle component level). This is really very hard (try to look into any semantic component less variables file to see how much stuff it defines)
